### PR TITLE
DEVOPS-179434: Update database account references in documentation

### PR DESCRIPTION
**Pull request by mrshanahan**
Since we are no longer formally exposing the SA user, we added a new sysadmin account. We also added the RelativityScriptLogin account. Neither of these were documented in the public docs, so we're adding them now.

### CODE REVIEW

**Comment by mrshanahan** [comment]
Temporarily unarchived this so we could do this last update to the docs.

**Review by jacob-carlson — DISMISSED** [review]
Reviewed the PDF and DOC .  Thanks Matt.

**Comment by mrshanahan** [comment]
Sorry, also updated CODEOWNERS so we don't have to bother Chandra. We can bypass that check for this PR.

**Review by jacob-carlson — APPROVED** [review]

**Review by alcott — APPROVED** [review]

**Comment by mrshanahan** [comment]
Just going to double-check that the doc updates are indeed accurate.

**Pull request merged**
